# The URL the site will be built for
base_url = "https://www.mollikka.net"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

taxonomies = [
    {name = "Language", render=false},
    {name = "tags"}
]

author = "Lauri Tervonen"
generate_feed = true
feed_filename = "rss.xml"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
languages = ["English", "Suomi"]

menu_items = [
    {name = "head", url = "/"},
    {name = "artwork", url = "/artwork", theme="themeBlue"},
    {name = "music", url = "/music"},
    {name = "design", url = "/design", theme="themeRed"},
    {name = "photos", url = "/photos"},
    {name = "text", url = "/text"},
]

social_links = [
    {name = "Flickr", url = "https://www.flickr.com/photos/mollikka/"},
    {name = "Tumblr", url = "https://moellikkae.tumblr.com/"},
    {name = "GitHub", url = "https://github.com/mollikka/"},
    {name = "SoundCloud", url = "https://soundcloud.com/lauri-tervonen"},
    {name = "Spoonflower", url = "https://www.spoonflower.com/profiles/moellikkae/"},
    {name = "Thingiverse", url = "https://www.thingiverse.com/stuffperson/"},
    {name = "Email", url = "lauri@mollikka.net"},
]